#!/bin/bash
#
# Execute setup script in same folder
SCRIPT_DIR=$( dirname "${BASH_SOURCE[0]}" )
source $SCRIPT_DIR/setup
#
# Set XDG tempopary folder for sudo_user
export XDG_RUNTIME_DIR=/tmp/runtime-$ME
#
# Execute VLBImonit.py
nohup python $APP_DIR/tools/andash.py -c $CONFIG_DIR/vlbi.toml > $PROBLEM_DIR/${0##*/}.$ME.txt 2>&1 &
