#!/bin/bash
#
# Execute setup script in same folder
source /sgpvlbi/progs/adap_v2/scripts/setup
#
# Set XDG tempopary folder for sudo_user
export XDG_RUNTIME_DIR=/tmp/runtime-$ME
#
# Execute
nohup python $APP_DIR/src/tools/andash.py -c $CONFIG_DIR/vlbi.toml > $PROBLEM_DIR/${0##*/}.$ME.txt 2>&1 &
