#!/usr/bin/csh
# Start virtual environment
source /sgpvlbi/progs/adap_v2/scripts/setup.csh
#
# Set XDG tempopary folder for sudo_user
setenv XDG_RUNTIME_DIR  /tmp/runtime-$SUDO_USER
#
# Set QT environment variables
setenv QT_LOGGING_RULES '*.debug=false;qt.qpa.*=false'

python $APP_DIR/src/aps -c $ADAP_CONFIG $argv #>& /dev/null

