#!/usr/bin/csh
# Start virtual enviroment
source /sgpvlbi/progs/adap_v2/scripts/setup.csh
#
# Set XDG tempopary folder for sudo_user
setenv XDG_RUNTIME_DIR  /tmp/runtime-$SUDO_USER
#
# Set QT environment variables
setenv QT_LOGGING_RULES '*.debug=false;qt.qpa.*=false'

python $APP_DIR/src/qaps2 -c $CONFIG_DIR/vlbi.toml $argv 
#>& /dev/null 

