#!/bin/bash
#
# Execute setup script in same folder
source /sgpvlbi/progs/set_adap

# Execute app
nohup python $APP_DIR/src/VLBIauxfiles.py -c $ADAP_CONFIG -q VLBIaux > $PROBLEM_DIR/${0##*/}.txt 2>&1 &
