#!/bin/bash
#
# Execute setup script in same folder
SCRIPT_DIR=$( dirname "${BASH_SOURCE[0]}" )
source $SCRIPT_DIR/setup

# Execute
nohup python $APP_DIR/src/VLBIchkskd.py -c $CONFIG_DIR/vlbi.toml -q VLBIchkskd -s '23:00' > $PROBLEM_DIR/${0##*/}.txt 2>&1 &
