#!/bin/bash
#
# Execute setup script in same folder
SCRIPT_DIR=$( dirname "${BASH_SOURCE[0]}" )
source $SCRIPT_DIR/setup
#
# Execute VLBImonit.py
python $APP_DIR/src/vgosdb/fetch.py -c $CONFIG_DIR/vlbi.toml $@
