#!/bin/bash
#
# Execute setup script in same folder
SCRIPT_DIR=$( dirname "${BASH_SOURCE[0]}" )
source $SCRIPT_DIR/setup

# Execute VLBImonit.py
nohup python $APP_DIR/src/VLBIintmonit.py -c $CONFIG_DIR/vlbi.toml -n $1 > $PROBLEM_DIR/${0##*/}.$1.txt 2>&1 &
