#!/bin/bash
#
# Execute setup script in same folder
SCRIPT_DIR=$( dirname "${BASH_SOURCE[0]}" )
source $SCRIPT_DIR/setup

# Execute
nohup python $APP_DIR/src/VLBIintmonit.py -c $ADAP_CONFIG -n $1 > $PROBLEM_DIR/${0##*/}.$1.txt 2>&1 &
