#!/bin/bash
#
# Execute setup script in same folder
SCRIPT_DIR=$( dirname "${BASH_SOURCE[0]}" )
source $SCRIPT_DIR/setup

# Execute
nohup python $APP_DIR/src/VLBIlogger.py -c $ADAP_CONFIG -l $CONFIG_DIR/logger.toml -q VLBIlogger > $PROBLEM_DIR/${0##*/}.txt 2>&1 &
