#!/bin/bash
#
# Execute setup script in same folder
SCRIPT_DIR=$( dirname "${BASH_SOURCE[0]}" )
source $SCRIPT_DIR/setup

# Execute VLBIlogger.py
nohup python $APP_DIR/src/VLBIlogger.py -c $CONFIG_DIR/vlbi.toml -l $CONFIG_DIR/logger.toml -q VLBIlogger > $PROBLEM_DIR/${0##*/}.txt 2>&1 &
