#!/bin/bash
#
# Create virtual environment and activate
python3 -m venv venv
source = venv/bin/activate
# Upgrade pip
python -m pip install --upgrade pip
# Install dependencies using pyproject.toml
python -m pip install pyproject.toml
