#!/bin/bash
#
export ME="${SUDO_USER:-${USER}_user}"
#
export APP_DIR=/sgpvlbi/progs/adap_v2
export CONFIG_DIR=/sgpvlbi/progs/config/adap
export PROBLEM_DIR=/sgpvlbi/progs/logs/adap/problems
export PYTHONPATH=$APP_DIR/src

export XDG_RUNTIME_DIR=/tmp/runtime-$ME

source $APP_DIR/venv/bin/activate
