#!/bin/bash
#
# Execute setup script in same folder
SCRIPT_DIR=$( dirname "${BASH_SOURCE[0]}" )
source $SCRIPT_DIR/setup

# Execute 
nohup python $APP_DIR/src/VLBIvmf.py -c $ADAP_CONFIG -q VLBIvmf > $PROBLEM_DIR/${0##*/}.txt 2>&1 &
