#!/usr/bin/bash 
#

export SUDO_USER="oper"
#source /home/oper/.bashrc
#export PATH
#export LD_LIBRARY_PATH
#
# Execute setup script in same folder
SCRIPT_DIR=$( dirname "${BASH_SOURCE[0]}" )
source $SCRIPT_DIR/setup

# Execute VLBIwatchdog.py
nohup python $APP_DIR/src/VLBIwatchdog.py -c $CONFIG_DIR/vlbi-nvi.toml > $PROBLEM_DIR/${0##*/}.txt 2>&1 &
