[Server]
credentials = "Rmberube:Password123!"
host = "localhost"
port = 5672
api = 15672
vhost = '/'

[Exchanges]
default = "VLBI"
log = "LOG"

[Problems]
queue = "VLBIproblems"
folder = "/sgpvlbi/progs/logs/adap/problems"
wait = 3600

