[Mail]
ivscc = "/home/oper/.credentials/ivscc.json"
ivsop = "/sgpvlbi/progs/adap/security/ivsop.json"

[DataBase]
ivscc = "mysql+pymysql://oper:oper@localhost/ivscc"
vlbi = "mysql+pymysql://oper:oper@localhost/vlbi"

[Messaging]
rabbitmq = "mberube:Password123!"

[Server]
bkg = "ivsincoming:vlbi2000"
opar = "ivsup:Nuts47bhpU$"

From oper@gs61av-vlbiprd01 Thu Dec  9 12:21:12 2021


